### ISSUE TITLE
Fans are turned off

### ISSUE THREAD

**Issue by ashkan-leo** [suvash/nixos-nvidia-cuda-python-docker-compose#1]
I am trying to do something similar, and I have noticed that the fans are turned off as soon as the driver is installed. Do you know how to solve this?

**Comment by suvash** [comment]
no ideas, but some pointers to begin with :
- The fan does not necessarily run when it's idle, there's no need for it. As per factory settings, the fan only starts after a certain threshold for GPU/core temp is exceeded. Check for your model/manufacturer details here. You might be used to running GPU fans all the time on Windows etc. via 3rd party tools. This is not super important unless you're overclocking, getting throttled etc.
- Check for fan and temp details via tools such as `nvidia-smi` or the 3rd party `nvtop`.
- Run a short GPU burn test and see if the fan starts up. ( https://github.com/suvash/nixos-nvidia-cuda-python-docker-compose/blob/main/02-nixos-docker-nvidia-setup.org#optionally-run-the-gpu-burn-cuda-stress-test )
- If that works well, check what happens when you run some GPU intensive workload.

I'll close this for the time being, but do feel free to continue the conversation.
